POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NDg3NjUzNDcsIm1vYmlsZSI6IjIwNi0xMjMtNDU2NyIsImlkIjoxOTE4OTI2MTg3MDU3NTE2NTQ0LCJleHAiOjE3NDg4NTE3NDcsImlhdCI6MTc0ODc2NTM0N30.g27QAsMT0baSDs6kmEeG-gvg3__z30keAp3DtiKXc34

{
  "dailyTrainTicketId": 1925007629416009700,
  "date": 1747724400000,
  "end": "New York City",
  "start": "Los Angeles",
  "tickets": [
    {
      "passengerId": 1918926588892811300,
      "passengerIdCard": "passenger_id7",
      "passengerName": "passenger7",
      "passengerType": "1",
      "seatTypeCode": "2"
    }
  ],
  "trainCode": "G2"
}

###

GET http://localhost:8000/business/confirm-order/query-line-count/1929093046104887296
Content-Type: application/json
token: {{token}}
